import type { WorkspaceData } from './types';
import { summarizeWorkspace,screenStatus } from './domain';
export function localAnswer(message:string,data:WorkspaceData):string{
  const summary=summarizeWorkspace(data);const q=message.toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  if(/precio|tarifa|cotiza|comisi/.test(q)){const matches=data.screens.filter(s=>q.includes(s.city.toLowerCase())||q.includes(s.name.toLowerCase()));const screens=matches.length?matches:data.screens;return screens.length?`Tarifas de referencia registradas: ${screens.slice(0,8).map(s=>`${s.name} (${s.city}): ${s.currency} ${s.monthlyRate.toLocaleString('es-AR')}/mes`).join('; ')}. La disponibilidad se confirma con el operador. En Cotizador podés agregar servicio, ajuste, comisión e impuestos; la comisión se calcula sobre la base ajustada. No se aplican descuentos ni cambios automáticamente.`:'Todavía no hay tarifas cargadas. Registrá pantallas y sus tarifas para preparar una propuesta en Cotizador.';}
  if(/inciden|problema|falla|manten/.test(q)){const open=data.incidents.filter(i=>i.status!=='resolved');return open.length?`Hay ${open.length} incidencias abiertas: ${open.slice(0,8).map(i=>`${i.title} (${i.priority}, ${i.assignee||'sin responsable'})`).join('; ')}. Revisá prioridad y vencimiento en Incidencias.`:'No hay incidencias abiertas registradas. Esto no prueba por sí solo que las pantallas estén operativas.';}
  if(/eviden|certif|reprodu/.test(q))return `Hay ${data.evidence.length} evidencias registradas, ${summary.verifiedEvidence} revisadas como verificadas y ${summary.recordedPlays.toLocaleString('es-AR')} reproducciones informadas por player y verificadas. Una foto acredita un instante, no toda la campaña. Las reproducciones no son audiencia.`;
  const city=data.screens.find(s=>q.includes(s.city.toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')))?.city;
  if(city){const screens=data.screens.filter(s=>s.city===city);return `${city}: ${screens.map(s=>`${s.name}, ${s.ownership==='own'?'propia':'de tercero'}, señal ${screenStatus(s)}, tarifa ${s.currency} ${s.monthlyRate.toLocaleString('es-AR')}/mes`).join('; ')}. Confirmá cupo y período antes de cerrar la propuesta.`;}
  return `Tu red tiene ${summary.screens} pantallas en ${summary.cities.length} ciudades: ${summary.online} con señal online reciente y ${summary.unknown} sin señal confirmada. Hay ${summary.activeCampaigns} campañas con estado activo y ${summary.openIncidents} incidencias abiertas. Puedo ayudarte con tarifas, ciudades, incidencias y evidencias registradas.`;
}
