import type { Bootstrap, Screen } from './types';
const base = (id: string) => ({ id, version: 1, createdAt: '2026-09-01T09:00:00.000Z', updatedAt: '2026-09-22T09:00:00.000Z' });
export function demoBootstrap(): Bootstrap {
 const locations = [
 ['Corrientes & Callao','Buenos Aires','CABA','Av. Corrientes 1800',-34.6044,-58.3921,'own'],
 ['Libertador Norte','Vicente López','Buenos Aires','Av. del Libertador 1400',-34.526,-58.475,'own'],
 ['Acceso a la ciudad','La Plata','Buenos Aires','Av. 7 & Calle 32',-34.903,-57.963,'own'],
 ['Paseo del Buen Pastor','Córdoba','Córdoba','Av. Hipólito Yrigoyen 300',-31.425,-64.186,'partner'],
 ['Pellegrini Central','Rosario','Santa Fe','Av. Pellegrini 1500',-32.956,-60.649,'partner'],
 ['Arístides Villanueva','Mendoza','Mendoza','Arístides Villanueva 400',-32.895,-68.854,'partner'],
 ['Costanera Sur','Mar del Plata','Buenos Aires','Boulevard Marítimo 3000',-38.01,-57.537,'own'],
 ['Acceso Ruta 3','Trelew','Chubut','Av. Hipólito Yrigoyen 900',-43.252,-65.312,'partner'],
 ['Alto Palermo · Indoor','Buenos Aires','CABA','Av. Santa Fe 3200',-34.588,-58.412,'own'],
 ['Centro comercial Norte','San Isidro','Buenos Aires','Av. Centenario 500',-34.467,-58.517,'partner'],
 ['Plaza Independencia','Tucumán','Tucumán','24 de Septiembre 450',-26.830,-65.204,'partner'],
 ['Mitre & Sarmiento','Salta','Salta','Mitre 350',-24.785,-65.410,'partner']
 ] as const;
 const screens: Screen[] = locations.map((l,i)=>({...base(`screen-${i+1}`),name:l[0],city:l[1],province:l[2],address:l[3],latitude:l[4],longitude:l[5],ownership:l[6],environment:i===8?'indoor':'outdoor',status:i===6?'maintenance':i===7?'unknown':i===10?'offline':'online',operatorId:l[6]==='own'?'operator-1':i===7?'operator-4':'operator-2',width:i===8?2:6,height:i===8?1:3,resolution:i===8?'1920 × 1080':'1536 × 768',slotSeconds:10,loopSeconds:120,operatingHours:18,monthlyRate:600000+i*75000,monthlyCost:180000+i*22000,currency:'ARS',lastSeen:i===7?'':new Date(Date.now()-(i===10?86400000:180000)).toISOString(),notes:'Ubicación y condiciones ilustrativas. Validar inventario real antes de comercializar.',externalId:`DEMO-${String(i+1).padStart(3,'0')}`}));
 return {user:{id:'demo-admin',name:'Equipo TNW',email:'demo@tnw.lol',role:'admin'},integrations:{database:false,storage:false,ai:false,telemetry:false,latinAd:false},audit:[],data:{screens,
 clients:[{...base('client-1'),name:'Martina Demo',company:'Estudio Horizonte · Demo',email:'martina@example.com',phone:'',type:'agency',notes:'Cliente ficticio de demostración.'},{...base('client-2'),name:'Nicolás Demo',company:'Nómada · Demo',email:'nicolas@example.com',phone:'',type:'direct',notes:'Cliente ficticio de demostración.'},{...base('client-3'),name:'Lucía Demo',company:'Agencia Sur · Demo',email:'lucia@example.com',phone:'',type:'agency',notes:'Cliente ficticio de demostración.'}],
 operators:[{...base('operator-1'),name:'TNW · Operación propia (demo)',city:'Buenos Aires',contact:'Equipo técnico',email:'operacion@example.com',phone:'',status:'active',notes:'Equipo ficticio.'},{...base('operator-2'),name:'Red Federal · Demo',city:'Córdoba',contact:'Agustín Demo',email:'federal@example.com',phone:'',status:'active',notes:'Operador ficticio; condiciones a confirmar.'},{...base('operator-3'),name:'Costa LED · Demo',city:'Mar del Plata',contact:'Victoria Demo',email:'costa@example.com',phone:'',status:'contacted',notes:'Contacto ficticio.'},{...base('operator-4'),name:'Patagonia Outdoor · Demo',city:'Trelew',contact:'Pablo Demo',email:'patagonia@example.com',phone:'',status:'negotiating',notes:'Prospección ilustrativa, no representa un operador real.'}],
 campaigns:[{...base('campaign-1'),name:'La ciudad se mueve',clientId:'client-1',screenIds:['screen-1','screen-2','screen-3','screen-9'],startDate:'2026-09-01',endDate:'2026-09-30',status:'active',budget:3600000,currency:'ARS',spotSeconds:10,playsTarget:64800,notes:'Campaña ficticia. Las reproducciones son un objetivo, no entrega medida.'},{...base('campaign-2'),name:'Primavera en ruta',clientId:'client-2',screenIds:['screen-4','screen-5','screen-6'],startDate:'2026-09-15',endDate:'2026-10-15',status:'active',budget:2900000,currency:'ARS',spotSeconds:10,playsTarget:50000,notes:'Campaña de ejemplo.'},{...base('campaign-3'),name:'Destino Patagonia',clientId:'client-3',screenIds:['screen-8'],startDate:'2026-10-01',endDate:'2026-10-31',status:'draft',budget:1600000,currency:'ARS',spotSeconds:10,playsTarget:15000,notes:'Pendiente de confirmar disponibilidad.'}],
 evidence:[{...base('evidence-1'),screenId:'screen-1',campaignId:'campaign-1',capturedAt:'2026-09-22T09:30:00Z',source:'manual',status:'verified',fileUrl:'/demo-proof.svg',notes:'Imagen ilustrativa generada para la demo. No certifica emisión real.',plays:0,sha256:''},{...base('evidence-2'),screenId:'screen-4',campaignId:'campaign-2',capturedAt:'2026-09-21T14:15:00Z',source:'manual',status:'pending',fileUrl:'/demo-proof.svg',notes:'Ejemplo de registro a revisar.',plays:0,sha256:''}],
 incidents:[{...base('incident-1'),screenId:'screen-7',title:'Revisar módulo de alimentación',priority:'high',status:'in_progress',assignee:'Equipo técnico · Demo',dueDate:'2026-09-24',notes:'Incidencia ilustrativa. Coordinación de visita técnica.'},{...base('incident-2'),screenId:'screen-11',title:'Sin señal reciente del reproductor',priority:'medium',status:'open',assignee:'Operaciones · Demo',dueDate:'2026-09-23',notes:'Verificar conectividad antes de confirmar disponibilidad.'}],
 opportunities:[{...base('opportunity-1'),name:'Circuito Capital Norte',city:'Buenos Aires',address:'Corredor norte · ubicación a definir',stage:'survey',owner:'Desarrollo · Demo',investment:18000000,monthlyRevenue:2600000,monthlyCost:850000,currency:'ARS',notes:'Escenario ficticio. Requiere relevamiento, permisos y acuerdo comercial.'},{...base('opportunity-2'),name:'Ampliación Patagonia',city:'Trelew',address:'Ubicación a relevar',stage:'idea',owner:'Alianzas · Demo',investment:12500000,monthlyRevenue:1800000,monthlyCost:650000,currency:'ARS',notes:'Escenario ficticio; demanda y costos no validados.'},{...base('opportunity-3'),name:'Nuevo punto Zona Oeste',city:'Morón',address:'Ubicación a relevar',stage:'permits',owner:'Operaciones · Demo',investment:9600000,monthlyRevenue:1500000,monthlyCost:500000,currency:'ARS',notes:'Demostración de seguimiento de habilitaciones.'}],
 quotes:[{...base('quote-1'),name:'Circuito AMBA · Octubre',clientId:'client-1',screenIds:['screen-1','screen-2','screen-3'],startDate:'2026-10-01',endDate:'2026-10-31',baseAmount:1800000,adjustmentPercent:0,agencyPercent:15,serviceAmount:180000,taxPercent:21,currency:'ARS',status:'draft',notes:'Valores ilustrativos. Sujeto a confirmación de disponibilidad y condiciones.'}]}};
}
