import { notFound } from 'next/navigation';
import { getReport } from '@/lib/reports';
import './report.css';
export const dynamic='force-dynamic';
export const metadata={title:'Reporte de campaña | TNW',robots:{index:false,follow:false},referrer:'no-referrer'};
const date=(s:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(s.length===10?s+'T12:00:00Z':s));
export default async function ReportPage({params}:{params:Promise<{token:string}>}){
  const {token}=await params;const report=await getReport(token);if(!report)notFound();
  const {campaign,screens,evidence,client,expiresAt}=report;const plays=evidence.filter(e=>e.source==='player').reduce((n,e)=>n+e.plays,0);
  return <main className="client-report"><header><a href="/" className="report-brand">tnw<span>®</span></a><span>REPORTE DE CAMPAÑA / ACCESO PRIVADO</span></header><section className="report-hero"><p className="report-eyebrow">TRANSPARENCIA, PANTALLA POR PANTALLA.</p><h1>{campaign.name}</h1><p>{client?.company||client?.name||'Campaña TNW'} · {date(campaign.startDate)} — {date(campaign.endDate)}</p><span className="report-tag">Enlace válido hasta {date(expiresAt)}</span></section><section className="report-stats"><div><strong>{screens.length}</strong><span>Pantallas de la campaña</span></div><div><strong>{evidence.length}</strong><span>Evidencias revisadas</span></div><div><strong>{plays.toLocaleString('es-AR')}</strong><span>Reproducciones informadas y verificadas</span></div></section><p className="report-note">Este reporte muestra exclusivamente registros revisados como verificados por el equipo. Una imagen acredita un instante; no certifica por sí sola toda la pauta. Las reproducciones proceden del player y no equivalen a personas alcanzadas.</p><section><h2>Ubicaciones</h2><div className="report-locations">{screens.map(s=><article key={s.id}><span>{s.city} / {s.province}</span><h3>{s.name}</h3><p>{s.address}</p><small>{s.width} × {s.height} m · {s.environment==='outdoor'?'Exterior':'Interior'}</small></article>)}</div></section><section><h2>Registro de evidencias</h2>{evidence.length===0?<p className="report-empty">Aún no hay evidencias verificadas para este período. El equipo podrá incorporar capturas y registros de reproducción.</p>:<div className="report-evidence">{evidence.map(e=><article key={e.id}>{e.fileUrl?<img src={`/api/report-file/${token}?id=${e.id}`} alt={`Evidencia de ${screens.find(s=>s.id===e.screenId)?.name||'pantalla'} tomada el ${date(e.capturedAt)}`}/>:<div className="report-player"><strong>{e.plays.toLocaleString('es-AR')}</strong><span>reproducciones informadas por player</span></div>}<div><small>{e.source==='player'?'PLAYER':e.source==='camera'?'CÁMARA':'CAPTURA MANUAL'} · VERIFICADA</small><h3>{screens.find(s=>s.id===e.screenId)?.name||'Pantalla'}</h3><p>{date(e.capturedAt)} · {new Date(e.capturedAt).toLocaleTimeString('es-AR',{timeZone:'America/Argentina/Buenos_Aires',hour:'2-digit',minute:'2-digit'})} ART</p>{e.sha256&&<small className="report-hash">SHA-256 · {e.sha256}</small>}</div></article>)}</div>}</section><footer><strong>TNW · Tu red, a la vista.</strong><span>Actualizado al abrir · {date(new Date().toISOString())}</span><p>Podés guardar este reporte como PDF desde la función Imprimir de tu navegador. El enlace puede ser revocado por el equipo.</p></footer></main>;
}
