'use client';
import { useEffect, useRef, useState } from 'react';
import { MapPin, Expand, Minus, Plus } from 'lucide-react';
import type { Screen } from '@/lib/types';
import type L from 'leaflet';
export default function NetworkMap({screens,selected,onSelect,compact=false}:{screens:Screen[];selected?:string;onSelect:(screen:Screen)=>void;compact?:boolean}){
 const element=useRef<HTMLDivElement>(null);const map=useRef<L.Map|null>(null);const group=useRef<L.LayerGroup|null>(null);const handler=useRef(onSelect);handler.current=onSelect;const [ready,setReady]=useState(false);const [error,setError]=useState(false);
 useEffect(()=>{let cancelled=false;let observer:ResizeObserver|undefined;import('leaflet').then(l=>{if(cancelled||!element.current||map.current)return;const m=l.map(element.current,{zoomControl:false,scrollWheelZoom:false,attributionControl:true}).setView([-35.2,-64.5],5);map.current=m;l.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>',maxZoom:19}).addTo(m);group.current=l.layerGroup().addTo(m);setReady(true);observer=new ResizeObserver(()=>{if(!cancelled&&map.current===m)m.invalidateSize();});observer.observe(element.current);}).catch(()=>setError(true));return()=>{cancelled=true;observer?.disconnect();map.current?.remove();map.current=null;group.current=null;};},[]);
 useEffect(()=>{if(!ready)return;import('leaflet').then(l=>{if(!map.current||!group.current)return;group.current.clearLayers();screens.forEach(s=>{const dot=l.divIcon({className:'tnw-marker-container',html:`<span class="tnw-marker ${s.ownership} ${s.id===selected?'selected':''} ${s.status==='maintenance'?'maintenance':''}">${s.ownership==='own'?'T':'P'}</span>`,iconSize:[30,30],iconAnchor:[15,15]});const marker=l.marker([s.latitude,s.longitude],{icon:dot,title:s.name,keyboard:true});const label=document.createElement('div');label.textContent=`${s.name} · ${s.city}`;marker.bindTooltip(label,{direction:'top',offset:[0,-15]}).on('click',()=>handler.current(s)).addTo(group.current!);});});},[screens,selected,ready]);
 useEffect(()=>{if(ready&&screens.length){import('leaflet').then(l=>{map.current?.fitBounds(l.latLngBounds(screens.map(s=>[s.latitude,s.longitude] as [number,number])),{padding:[50,50],maxZoom:12});});}},[ready,screens.length]);
 const fit=()=>{if(!screens.length)return;void import('leaflet').then(l=>map.current?.fitBounds(l.latLngBounds(screens.map(s=>[s.latitude,s.longitude] as [number,number])),{padding:[50,50],maxZoom:12}));};
 return <div className={`network-map ${compact?'compact':''}`}><div ref={element} className="map-canvas" aria-label="Mapa de ubicaciones de pantallas"/>{(!ready||error)&&<div className="map-loading"><MapPin size={28}/>{error?'No se pudo cargar el mapa. El inventario sigue disponible.':'Preparando mapa de la red…'}</div>}<div className="map-label"><span className="live-dot"/>COBERTURA DE RED</div><div className="map-controls"><button aria-label="Acercar mapa" onClick={()=>map.current?.zoomIn()}><Plus size={17}/></button><button aria-label="Alejar mapa" onClick={()=>map.current?.zoomOut()}><Minus size={17}/></button><button aria-label="Ver todas las pantallas" onClick={fit}><Expand size={16}/></button></div><div className="map-legend"><span><i/>Propia</span><span><i className="partner"/>Asociada</span><small>{screens.length} ubicaciones</small></div></div>;
}
